<!--fooder共通 -->
<footer>
    <p>春日町診療所</p>
    <div>
        <dl>
            <dt>
                所在地：
            </dt>
            <dt>
                連絡先：
            </dt>
            <dt>
                駐車場：
            </dt>
            <dt>
                診療科：
            </dt>
        </dl>
        <dl>
            <dd>
                〒174-0074 東京都練馬区春日町3-29-401-102
            </dd>
            <dd>
                03-3999-8810
            </dd>
            <dd>
                10台（無料）
            </dd>
            <dd>
                内科/皮膚科/アレルギー科/リマウチ科
            </dd>
        </dl>
    </div>
</footer>
</body>
</html>